# Project information
site_name: Documentation
site_description: Next-generation SIP Server
site_author: Pedro Sanders
site_url: https://routr.io/docs

# Repository
repo_name: fonoster/routr
repo_url: https://github.com/fonoster/routr
edit_uri: /fonoster/routr/edit/master/docs/

nav:
  - Introduction:
    - Overview: introduction/overview.md
    - Installation: introduction/installation.md
    - Comparison to Alternatives: introduction/comparison.md
    - Community: introduction/community.md
    - FAQ: introduction/faq.md
    - Roadmap: introduction/roadmap.md
    - Media: introduction/media.md
    - Glossary: introduction/glossary.md
  - Concepts: concepts.md
  - Configuration:
    - General Configuration:
      - Transport Settings: configuration/general/transport.md
      - Signaling Security(TLS): configuration/general/signaling-security.md
      - Restful API: configuration/general/restful-api.md
      - Datasource Setting: configuration/general/datasource.md
      - Logging: configuration/general/logging.md
    - Users Configuration: configuration/users.md
    - Carriers(Gateways) Configuration: configuration/gateways.md
    - Virtual Numbers(DIDs) Configuration: configuration/dids.md
    - Domains Configuration: configuration/domains.md
    - Agents Configuration: configuration/agents.md
    - Peers Configuration: configuration/peers.md
  - Administration:
    - Command-Line: administration/cli.md
    - Web Console: administration/webconsole.md
  - API:
    - Reference: api/reference.md
    - Resources: api/resources.md
  - Guides:
    - Basic Setup: guides/basic-setup.md
    - Routr as Asterisk frontend: guides/routr-as-asterisk-frontend.md
    - Routr as FreeSWITCH frontend: guides/routr-as-freeswitch-frontend.md
    - Securing the Signaling Path: guides/securing-the-signaling-path.md
    - Running with Docker or Compose: guides/running-with-docker-or-compose.md
    - Running on Kubernetes: guides/running-on-kubernetes.md
    - Benchmarking: guides/benchmarking.md

# Copyright
copyright: 'Copyright &copy; 2018 Fonoster Inc'
theme:
  name: material
  custom_dir: docs/theme

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  palette:
    primary: blue grey
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: /assets/images/favicon.ico

extra:
  social:
    - type: globe
      link: https://fonoster.com
    - type: github-alt
      link: https://github.com/fonoster
    - type: twitter
      link: https://twitter.com/fonoster
    - type: linkedin
      link: https://www.linkedin.com/company/fonoster/about/

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
