# Project information
site_name: Documentation
site_description: Next-generation SIP Server
site_author: Pedro Sanders
site_url: https://routr.io/docs
google_analytics: ['UA-71722942-3', 'routr.io']

# Repository
repo_name: fonoster/routr
repo_url: https://github.com/fonoster/routr
edit_uri: /fonoster/routr/edit/master/docs/

nav:
  - Introduction:
    - Overview: introduction/overview.md
    - Installation: introduction/installation.md
    - Comparison to Alternatives: introduction/comparison.md
    - Community: introduction/community.md
    - FAQ: introduction/faq.md
    - Roadmap: introduction/roadmap.md
    - Media: introduction/media.md
    - Performance Tests:
      - User Location: introduction/performance-tests/user-location.md
    - Glossary: introduction/glossary.md
  - Concepts: concepts.md
  - Configuration:
    - General Configuration: configuration/general.md
    - Users Configuration: configuration/users.md
    - Carriers(Gateways) Configuration: configuration/gateways.md
    - Numbers(DID/DOD) Configuration: configuration/numbers.md
    - Domains Configuration: configuration/domains.md
    - Agents Configuration: configuration/agents.md
    - Peers Configuration: configuration/peers.md
  - Administration:
    - Command-Line:
      - Installation: administration/cli/installation.md
      - Cheatsheet: administration/cli/cheatsheet.md
      - Remote Access to a Routr Server: administration/cli/remote-access.md
    - Web Console: administration/webconsole.md
  - Rest API:
    - Overview: api/overview.md
    - Credentials: api/token.md
    - Location:
      #- create: api/location/create.md
      #- delete: api/location/delete.md
      - list: api/location/list.md
    - Registry: api/registry.md
    - Agents:
      - create: api/agents/create.md
      - delete: api/agents/delete.md
      - get: api/agents/get.md
      - list: api/agents/list.md
      - update: api/agents/update.md
    - Peers:
      - create: api/peers/create.md
      - delete: api/peers/delete.md
      - get: api/peers/get.md
      - list: api/peers/list.md
      - update: api/peers/update.md
    - Domains:
      - create: api/domains/create.md
      - delete: api/domains/delete.md
      - get: api/domains/get.md
      - list: api/domains/list.md
      - update: api/domains/update.md
    - Gateways:
      - create: api/gateways/create.md
      - delete: api/gateways/delete.md
      - get: api/gateways/get.md
      - list: api/gateways/list.md
      - update: api/gateways/update.md
    - Numbers:
      - create: api/numbers/create.md
      - delete: api/numbers/delete.md
      - get: api/numbers/get.md
      - list: api/numbers/list.md
      - update: api/numbers/update.md
    - Configuration:
      - Get: api/config/get.md
      - Update: api/config/update.md
    - System:
      - Status:
        - Get: api/status/get.md
        - Update: api/status/update.md
      - Info: api/sys/info.md
      - Logs: api/sys/logs.md
  - Guides:
    - Basic Setup: guides/basic-setup.md
    - Routr as Asterisk frontend: guides/routr-as-asterisk-frontend.md
    #- Routr as FreeSWITCH frontend: guides/routr-as-freeswitch-frontend.md
    - Securing the Signaling Path: guides/securing-the-signaling-path.md
    - Running with Docker or Compose: guides/running-with-docker-or-compose.md
    - Running on Kubernetes: guides/running-on-kubernetes.md
    - Benchmarking: guides/benchmarking.md

# Copyright
copyright: 'Copyright &copy; 2021 Fonoster Inc'
theme:
  name: material
  custom_dir: docs/theme

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  palette:
    primary: blue grey
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: /assets/images/favicon.ico
  icon:
    logo: "\uE80C"
extra:
  social:
    - type: globe
      link: https://fonoster.com
    - type: github-alt
      link: https://github.com/fonoster
    - type: twitter
      link: https://twitter.com/fonoster
    - type: linkedin
      link: https://www.linkedin.com/company/fonoster/about/

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
