apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-routr-registry-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
data:
  registry.yaml: |-
    kind: Registry
    apiVersion: v2beta1
    spec:
      requesterAddr: {{ .Release.Name }}-routr-requester.{{ .Release.Namespace }}:51909
      apiAddr: {{ .Release.Name }}-routr-apiserver.{{ .Release.Namespace }}:51907
      registerInterval: {{ .Values.registry.registerInterval }}
      cache:
      {{- if eq .Values.registry.cache.provider "redis" }}
        provider: redis
        {{- if .Values.registry.cache.parameters }}
        parameters: {{ .Values.registry.cache.parameters }}
        {{- else }}
        parameters: host={{ .Release.Name }}-redis-master.{{ .Release.Namespace }},port=6379
        {{- end }}
      {{- else }}  
        provider: memory
      {{- end }}
      {{- if .Values.registry.methods }}
      methods: 
      {{- range .Values.registry.methods }}
        - {{.}}
      {{- end }}
      {{- end }}
      edgePorts:
        - address: {{ .Release.Name }}-routr-edgeport.{{ .Release.Namespace }}:5060
