apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-routr-rtprelay
  namespace: {{ .Release.Namespace }}
  {{- with .Values.rtprelay.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
spec:
  ports:
  - port: 51903
    targetPort: 51903
  selector:
    {{- include ".helm.selectorLabels" . | nindent 6 }}