- apiVersion: v1draft1
  kind: Agent
  metadata:
    name: John Doe
  spec:
    credentials:
      username: '1001'
      secret: '1234'
    domains: [sip.local]
- apiVersion: v1draft1
  kind: Agent
  metadata:
    name: Janie Doe
  spec:
    credentials:
      username: '1002'
      secret: '1234'
    domains: [sip.local]
- apiVersion: v1draft1
  kind: Agent
  metadata:
    name: Janie Doe
  spec:
    credentials:
      username: '4001'
      secret: '1234'
    domains: [sip2.local]
