- apiVersion: v1draft1
  kind: Gateway
  metadata:
    name: Provider Inc.
  spec:
    regService:
      host: sip.provider.net
      credentials:
        username: 'youruser'
        secret: 'yoursecret'
      transport: udp
