- apiVersion: v1beta1
  kind: Gateway
  metadata:
    ref: gw50a1a4ca
    name: Provider Inc.
  spec:
    host: sip.provider.net
    port: 5061
    transport: tcp
    credentials:
      username: 'pbx-1'
      secret: '1234'
- apiVersion: v1beta1
  kind: Gateway
  metadata:
    name: Provider Inc.
  spec:
    host: sip2.provider.net
    transport: tcp
