- apiVersion: v1beta1
  kind: Number
  metadata:
    ref: dd76afc94b
    gwRef: gw50a1a4ca
    geoInfo:                  # Replace this using your DID's info
      city: City, State
      country: Country
      countryISOCode: US
  spec:
    location:
      telUrl: 'tel:0000000000'        # Use your DID number as given by your provider
      aorLink: 'sip:1001@sip.local'
