apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-routr-dispatcher
  namespace: {{ .Release.Namespace }}  
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
    service: dispatcher
spec:
  selector:
    matchLabels:
      {{- include ".helm.selectorLabels" . | nindent 6 }}
      service: dispatcher
  template:
    metadata:
      annotations: 
      {{- with .Values.dispatcher.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/dispatcher/configmaps.yaml") . | sha256sum }}
      labels:
        {{- include ".helm.selectorLabels" . | nindent 8 }}
        service: dispatcher
    spec:
      securityContext:
        runAsUser: {{ .Values.dispatcher.securityContext.runAsUser }}
        runAsGroup: {{ .Values.dispatcher.securityContext.runAsGroup }}
        fsGroup: {{ .Values.dispatcher.securityContext.fsGroup }}
      containers:
        - name: dispatcher
          image: "{{ .Values.dispatcher.image.repository }}:{{ .Values.dispatcher.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.dispatcher.image.pullPolicy }}
          livenessProbe:
            exec:
              command: ["healthcheck"]
            initialDelaySeconds: {{ .Values.dispatcher.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.dispatcher.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.dispatcher.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.dispatcher.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.dispatcher.livenessProbe.timeoutSeconds }}
          env:
            - name: CONFIG_PATH
              value: /etc/routr/dispatcher.yaml
            - name: LOGS_LEVEL
              value: {{ .Values.global.logsLevel }}
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: {{ .Values.global.otlExporter }}
          ports:
            - containerPort: 51901
          volumeMounts:
            - name: config
              mountPath: /etc/routr/dispatcher.yaml
              subPath: dispatcher.yaml
          resources:
            {{- if .Values.dispatcher.resources.limits }}
            limits:
            {{- .Values.dispatcher.resources.limits | toYaml | nindent 12 }}
            {{- end }}
            {{- if .Values.dispatcher.resources.requests }}
            requests:
            {{- .Values.dispatcher.resources.requests | toYaml | nindent 12 }}
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.dispatcher.securityContext.allowPrivilegeEscalation }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-routr-dispatcher-config
